### ISSUE TITLE
Regarding your repository pattern.

### ISSUE THREAD

**Issue by JamesLoyd** [rahulpnath/Blog#1]
I keep getting Repositories.IDataStoreContext, is an interface and cannot be constructed. Are you missing a type mapping? 

I made the Interfaces for strategy and  into ones that accept generic arguments as well as UnitOfWork and IUnitOfWork.

Is there something wrong with how dependency injection is being handled?

**Comment by rahulpnath** [comment]
The code for this just shows the implementation structure and does not have the full implementation. Have you wired up the container with all the registrations needed at the start of the program. 

From the Program.cs below is the place you would need to setup all the registrations for the container
 IUnityContainer container = new UnityContainer();
// set up the container here 

If you are new to unity you could check this [post](http://www.rahulpnath.com/blog/ioc-registration-by-convention/) on how the registrations could be done

Let me know if that helps

**Comment by JamesLoyd** [comment]
I followed your code in the IoCConvention code that you reference in that blog post. So for the part of the code that says

``` Csharp
public static void RegisterByConvention(IUnityContainer container, IEnumerable<Assembly> assembliesToLoad = null)`
```

I would pass the main assembly to it?

**Comment by rahulpnath** [comment]
It is an optional parameter, if assemblies to load is null it gets all the assemblies from the base path. If this is a web application then this needs to be updated though i guess

Yeah basically the idea is that it scans all the assemblies for the classes to register. You can also do manual registrations using [code or config file](http://www.rahulpnath.com/blog/configuring-unity-container-comparing-code-and-xml-configuration-side-by-side/) if you do not want a convention based registration

**Comment by rahulpnath** [comment]
Hope this issue is solved. Feel free to reopen if you need any other details
