### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by chintan3100** [rahulpnath/Blog#2]
I am using Powershell 5.* but it's not working. (Create AD with certificate using powershell)
Can you please provide latest version

**Comment by rahulpnath** [comment]
Can you check if the below work

$certificateFilePath = "C:\certificates\ADTestVaultApplication.cer"
$certificate = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2
$certificate.Import($certificateFilePath)
$rawCertificateData = $certificate.GetRawCertData()
$credential = [System.Convert]::ToBase64String($rawCertificateData)
$startDate= [System.DateTime]::Now
$endDate = $startDate.AddYears(1)
$adApplication = New-AzureRmADApplication -DisplayName "CertAdApplication" -HomePage  "http://www.test.com" -IdentifierUris "http://www.test.com" -CertValue $credential  -StartDate $startDate -EndDate $endDate

$servicePrincipal = New-AzureRmADServicePrincipal -ApplicationId $adApplication.ApplicationId

Set-AzureRmKeyVaultAccessPolicy -VaultName 'RahulKeyVault' -ServicePrincipalName $servicePrincipal

**Comment by chintan3100** [comment]
Thanks It's work,

Please update below line for enhance 
$startDate= [System.DateTime]$certificate.GetEffectiveDateString()
$endDate= ([System.DateTime]$certificate.GetExpirationDateString()).AddDays(-1)

If current date not matched with certificate it not work
